### ISSUE TITLE
Errors Best Practices

### ISSUE THREAD

**Issue by GeorgeMac** [codeship/go-best-practice#11]
we need a section around errors and error handling best practices.

**Comment by brettbuddin** [comment]
I'll take the first crack at this one. I have opinions.

**Comment by GeorgeMac** [comment]
I would like to propose we hold `github.com/pkg/errors` in high regard and use it where applicable.

**Comment by GeorgeMac** [comment]
Having consensus on how we structure error messaging should be documented here.

My proposals are:
1. all lower case
2. no punctuation (as with comments)
3. avoid using the word `error` in an error (taking inspiration from lack of stutter)

For example:

`errors.New("Error: fetching important information.")`

becomes:

`errors.New("fetching important information")`

**Comment by brettbuddin** [comment]
I'm interested in using Cheney's work with errors, but haven't had much experience with it just yet. For a rundown on *why* a package like `gitHub.com/pkg/errors` exists: https://dave.cheney.net/2016/04/27/dont-just-check-errors-handle-them-gracefully

**Comment by GeorgeMac** [comment]
#18

**Comment by GeorgeMac** [comment]
Merged the error section
