### ISSUE TITLE
Common Makefile

### ISSUE THREAD

**Issue by markphelps** [codeship/go-best-practice#14]
Should we use a common 'starter' Makefile for our projects?

I am partial to one that I've been using in my personal projects [here](https://github.com/markphelps/example/blob/master/Makefile)

But obviously open to suggestions

**Comment by brettbuddin** [comment]
Either this or a `bin/` directory with scripts in order to get command flag behaviors that are a bit more elegant than overriding environment variables for Makefile tasks.

**Comment by GeorgeMac** [comment]
I would be happy with either and I am not fussy either way.

**Comment by GeorgeMac** [comment]
You could call it a Markfile and leave your "mark" like "he who shall not be named". Mostly because his name is already used throughout all the codeship codebases and it goes without saying.

**Comment by GeorgeMac** [comment]
#16
